# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4a7a8961d8b5697a9502c91d113c0475053ee8be63127692780f6ad5147677dbcb4e2358e9d79eff6a359521f391d1e6c75221f0e8e9166b847c1d1a9357506

test:
  secret_key_base: 29840c7783f0a8dfd5cb6fbdd6c704ad4bf752e3fce35ebab688f66166ea48f5f3db716911b8fb6811e14f011535031fa419111bbaa4444e204341f9e561cbae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
